In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
# synthetic dataset creation
X, y = make_classification(
    n_samples=10, # no. of samples
    n_features=2, # features count
    n_informative=2, # no. of informative features
    n_redundant=0, # redundant features
    n_classes=2, # no. of classes
    random_state=43
)

In [4]:
X

array([[ 1.03884994,  0.00663148],
       [ 0.21669994,  1.54039882],
       [-1.03850553, -1.8291124 ],
       [ 2.00998363, -0.15247943],
       [-1.22554526, -1.21041874],
       [ 0.73984628, -0.95783455],
       [ 1.94398105,  2.25342249],
       [ 1.5087201 ,  1.12545049],
       [-1.17860139, -0.59927223],
       [-1.29267047,  0.49699535]])

In [5]:
# convert: np.array() --> torch.tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [6]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0] # rows count
        
    def __getitem__(self, index):
        return self.features[index], self.labels[index]
        

In [7]:
dataset = CustomDataset(features=X, labels=y)

In [8]:
len(dataset)

10

In [9]:
dataset[1]

(tensor([0.2167, 1.5404]), tensor(0))

In [10]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [11]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*20)

tensor([[-1.2255, -1.2104],
        [ 2.0100, -0.1525]])
tensor([0, 1])
--------------------
tensor([[1.9440, 2.2534],
        [1.5087, 1.1255]])
tensor([1, 1])
--------------------
tensor([[-1.2927,  0.4970],
        [ 0.7398, -0.9578]])
tensor([0, 1])
--------------------
tensor([[-1.1786, -0.5993],
        [ 0.2167,  1.5404]])
tensor([0, 0])
--------------------
tensor([[ 1.0388,  0.0066],
        [-1.0385, -1.8291]])
tensor([1, 0])
--------------------
