In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/breast-cancer-dataset/breast-cancer.csv


In [2]:
df = pd.read_csv('/kaggle/input/breast-cancer-dataset/breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
df.shape

(569, 32)

In [4]:
df.drop(columns=['id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
# scaling
scaler = StandardScaler() # mean centering

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train[0]

array([-1.34851126,  0.41067617, -1.33793275, -1.11883524,  0.52161693,
       -0.55270419, -0.8726648 , -0.91458007, -0.38091855,  0.82531271,
       -0.60776922,  1.58336154, -0.59167923, -0.56643834,  1.12514423,
       -0.47124687, -0.50246457, -0.42992762,  0.28773565,  0.12473971,
       -1.23185931,  0.97933833, -1.21893951, -0.98081464,  0.93635652,
       -0.60254411, -0.88646016, -0.80279029, -0.0513471 ,  0.39211275])

In [8]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,

Currently our data is in np.array() we need to convert it to tensors

In [10]:
# np.array() -> tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [12]:
X_train_tensor[0]

tensor([-1.3485,  0.4107, -1.3379, -1.1188,  0.5216, -0.5527, -0.8727, -0.9146,
        -0.3809,  0.8253, -0.6078,  1.5834, -0.5917, -0.5664,  1.1251, -0.4712,
        -0.5025, -0.4299,  0.2877,  0.1247, -1.2319,  0.9793, -1.2189, -0.9808,
         0.9364, -0.6025, -0.8865, -0.8028, -0.0513,  0.3921],
       dtype=torch.float64)

In [13]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [14]:
# dataset
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [15]:
# dataloaders
train_data_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_data_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#### Model Definition

In [16]:
# class firstNN():

#     # constructor
#     def __init__(self, X):
#         self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#         self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

#     def forward_pass(self, X):
#         z = torch.matmul(X, self.weights) + self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred

#     def calculate_loss(self, y_pred, y):
#         epsilon = 1e-7
#         y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # to prevent log(0)

#         loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
#         return loss

import torch.nn as nn

class firstUpdatedNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        output = self.linear(features)
        output = self.sigmoid(output)
        return output
        

In [17]:
# parameters
learning_rate = 0.01
epochs = 15

loss_function = nn.BCELoss()

In [18]:
# training  pipeline
model = firstUpdatedNN(X_train_tensor.shape[1])

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# for epoch in range(epochs):
#     # froward prop
#     y_pred = model(X_train_tensor.float())
    
#     # calc. loss
#     loss = loss_function(y_pred, y_train_tensor.view(-1, 1).float())
    
#     optimizer.zero_grad() # clear gradients
    
#     # backward pass
#     loss.backward() # pytorch's backward prop functionality
    
#     # update params
#     optimizer.step() # parameters will get updated

#     # zero gradients - to disable the gradient accumulation
#     # model.linear.weight.grad.zero_()
#     # model.linear.bias.grad.zero_()

#     print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

In [19]:
for epoch in range(epochs):
    for batch_features, batch_labels in train_data_loader:
        # forward pass
        y_pred = model(batch_features.float())

        # calc. loss
        loss = loss_function(y_pred, batch_labels.view(-1, 1).float())

        # clear gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # parameters update
        optimizer.step()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.2584208846092224
Epoch: 2, Loss: 0.1477624475955963
Epoch: 3, Loss: 0.04539912939071655
Epoch: 4, Loss: 0.10052534192800522
Epoch: 5, Loss: 0.18665240705013275
Epoch: 6, Loss: 0.09379034489393234
Epoch: 7, Loss: 0.0876447781920433
Epoch: 8, Loss: 0.15330946445465088
Epoch: 9, Loss: 0.3535640239715576
Epoch: 10, Loss: 0.03447628393769264
Epoch: 11, Loss: 0.01942082867026329
Epoch: 12, Loss: 0.03885277360677719
Epoch: 13, Loss: 0.05852842330932617
Epoch: 14, Loss: 0.023747622966766357
Epoch: 15, Loss: 0.10098874568939209


In [20]:
# evaluation using test_loader
model.eval() # set to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_data_loader:
        # forward pass
        y_pred = model(batch_features.float())
        y_pred = (y_pred > 0.8).float()

        # calculate accuracy
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy: .4f}")

Accuracy:  0.9236


In [21]:
# evaluation
# with torch.no_grad():
#     y_pred = model(X_test_tensor.float())

In [22]:
# y_pred = (y_pred > 0.4).float()
# accuracy = (y_pred == y_test_tensor).float().mean()
# accuracy