In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/breast-cancer-dataset/breast-cancer.csv


In [2]:
df = pd.read_csv('/kaggle/input/breast-cancer-dataset/breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
df.shape

(569, 32)

In [4]:
df.drop(columns=['id'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
# scaling
scaler = StandardScaler() # mean centering

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train[0]

array([-6.83361285e-01,  5.55163287e-01, -7.22576815e-01, -6.50632264e-01,
       -6.89885832e-01, -1.05388086e+00, -9.08516974e-01, -9.80796100e-01,
       -1.17879448e+00, -5.39156782e-01, -9.34116852e-03, -1.85291169e-02,
       -1.24924553e-01, -2.59726370e-01, -4.00485069e-01, -8.71691504e-01,
       -6.51780647e-01, -7.18842321e-01,  4.18509925e-01, -7.48304959e-01,
       -6.90968432e-01,  4.10850697e-04, -7.35633738e-01, -6.42411532e-01,
       -1.03550537e+00, -1.06847172e+00, -1.04154488e+00, -1.19669675e+00,
       -7.79605411e-01, -1.00169236e+00])

In [8]:
# Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,

Currently our data is in np.array() we need to convert it to tensors

In [10]:
# np.array() -> tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [12]:
X_train_tensor[0]

tensor([-6.8336e-01,  5.5516e-01, -7.2258e-01, -6.5063e-01, -6.8989e-01,
        -1.0539e+00, -9.0852e-01, -9.8080e-01, -1.1788e+00, -5.3916e-01,
        -9.3412e-03, -1.8529e-02, -1.2492e-01, -2.5973e-01, -4.0049e-01,
        -8.7169e-01, -6.5178e-01, -7.1884e-01,  4.1851e-01, -7.4830e-01,
        -6.9097e-01,  4.1085e-04, -7.3563e-01, -6.4241e-01, -1.0355e+00,
        -1.0685e+00, -1.0415e+00, -1.1967e+00, -7.7961e-01, -1.0017e+00],
       dtype=torch.float64)

#### Model Definition

In [13]:
# class firstNN():

#     # constructor
#     def __init__(self, X):
#         self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#         self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

#     def forward_pass(self, X):
#         z = torch.matmul(X, self.weights) + self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred

#     def calculate_loss(self, y_pred, y):
#         epsilon = 1e-7
#         y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # to prevent log(0)

#         loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
#         return loss

import torch.nn as nn

class firstUpdatedNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        output = self.linear(features)
        output = self.sigmoid(output)
        return output

    def calculate_loss(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # to prevent log(0)

        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss
        

In [14]:
# parameters
learning_rate = 0.01
epochs = 15

In [15]:
# training  pipeline
model = firstUpdatedNN(X_train_tensor.shape[1])

for epoch in range(epochs):
    # froward prop
    y_pred = model(X_train_tensor.float())
    
    # calc. loss
    loss = model.calculate_loss(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward() # pytorch's backward prop functionality
    
    # update params
    with torch.no_grad():
        model.linear.weight  -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad

    # zero gradients - to disable the gradient accumulation
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.742034912109375
Epoch: 2, Loss: 0.7403608560562134
Epoch: 3, Loss: 0.7387558817863464
Epoch: 4, Loss: 0.737217128276825
Epoch: 5, Loss: 0.7357420325279236
Epoch: 6, Loss: 0.7343279123306274
Epoch: 7, Loss: 0.7329718470573425
Epoch: 8, Loss: 0.7316717505455017
Epoch: 9, Loss: 0.7304249405860901
Epoch: 10, Loss: 0.7292290925979614
Epoch: 11, Loss: 0.7280821800231934
Epoch: 12, Loss: 0.7269816994667053
Epoch: 13, Loss: 0.725925624370575
Epoch: 14, Loss: 0.7249119877815247
Epoch: 15, Loss: 0.7239387631416321


In [16]:
# evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor.float())

In [17]:
y_pred = (y_pred > 0.4).float()
accuracy = (y_pred == y_test_tensor).float().mean()
accuracy

tensor(0.4160)