In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
import torch.nn as nn

In [3]:
# create model
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__() # parent class constructor inherit
        self.linear = nn.Linear(num_features, 1) # input = num_features, output = 1 (single neuron)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        output = self.linear(features) # wx+b
        output = self.sigmoid(output)
        return output
        

In [4]:
# sample dataset
features = torch.rand(10, 5) # 10 rows, 5 cols

# create model object
model = Model(features.shape[1])

# forward pass
model(features) # same as model.forward(features) done using magic calls internally

tensor([[0.4244],
        [0.4629],
        [0.4124],
        [0.4330],
        [0.4578],
        [0.4351],
        [0.4659],
        [0.4244],
        [0.4566],
        [0.4527]], grad_fn=<SigmoidBackward0>)

In [5]:
# get weights
# model.linear.weight
model.linear.bias

Parameter containing:
tensor([-0.1965], requires_grad=True)

In [6]:
!pip install torchinfo

In [7]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Building bigger model

#### Flow
5 inputs --> 1st hidden layer (3 neurons + relu) --> sigmoid (output layer) --> y_pred

In [8]:
# create model
# class Model(nn.Module):
#     def __init__(self, num_features):
#         super().__init__() # parent class constructor inherit
#         self.linear1 = nn.Linear(num_features, 3)
#         self.relu = nn.ReLU()
#         self.linear2 = nn.Linear(3, 1)
#         self.sigmoid = nn.Sigmoid()

#     def forward(self, features):
#         output = self.linear1(features) # wx+b
#         output = self.relu(output)
#         output = self.linear2(output)
#         output = self.sigmoid(output)
#         return output


# using sequential container to perform the forward pass
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__() # parent class constructor inherit
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        output = self.network(features)
        return output

In [9]:
# sample dataset
features = torch.rand(10, 5) # 10 rows, 5 cols

# create model object
model = Model(features.shape[1])

# forward pass
model(features) # same as model.forward(features) done using magic calls internally

tensor([[0.3819],
        [0.4081],
        [0.3935],
        [0.3789],
        [0.3795],
        [0.4141],
        [0.3792],
        [0.3824],
        [0.4165],
        [0.4020]], grad_fn=<SigmoidBackward0>)

In [10]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00