In [1]:
import torch
torch.__version__

'2.9.0+cpu'

#### Creating a Tensor

In [3]:
# using empty
t = torch.empty(2,3) # allocates the space in memory to create a tensor of given space

In [ ]:
type(t) # type of data structure

torch.Tensor

In [5]:
# using zeros - to create a tensor where all values = 0
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# similarly to create a tensor where values = 1
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# if we want to randomly intialize the the values, range - [0, 1]
torch.rand(2, 3)

tensor([[5.9841e-01, 5.7665e-01, 4.5210e-04],
        [4.3427e-02, 1.6893e-01, 4.6340e-01]])

In [8]:
# now if the run the above cell multiple times then the generated values will be different every time. so if we want it to generate
# same random values every time then we must use manual_seed. Similar to what we do in ML during train test split's "random_state"
torch.manual_seed(1337)
torch.rand(1, 3)

tensor([[0.0783, 0.4956, 0.6231]])

In [9]:
# for cutom tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange -> ", torch.arange(0, 10, 2)) # generates a 1D tensor with provided jump

# linspace (linearly spaced)
print("using linspace -> ", torch.linspace(0, 10, 10)) # linearly spaced n-values within a given range

# eye
print("using eye -> ", torch.eye(5)) # identity matrix

# full
print('using full -> ', torch.full((3, 3), 5)) # shape of tensor with a given value at every index

using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
