### Scalar Operation

In [9]:
import torch # type: ignore
x = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
# addition
x + 2

# subtraction
x - 2

# multiplication
x * 3

# division
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [11]:
# int division
(x*100) // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

### Element wise Operation

In [12]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [13]:
print(a)
print(b)

tensor([[0.7815, 0.4103, 0.1317],
        [0.7118, 0.4271, 0.9830]])
tensor([[0.1724, 0.3666, 0.2044],
        [0.6603, 0.8798, 0.3481]])


In [14]:
# addition
a+b

# subtraction
a-b

# multiplication
a*b

# division
a/b

# power
a ** b

tensor([[0.9584, 0.7214, 0.6608],
        [0.7990, 0.4731, 0.9940]])

In [15]:
## other operations

c = torch.tensor([1, -2, 3, -4])

# abs
torch.abs(c)

tensor([1, 2, 3, 4])

### Reduction Operation

In [16]:
e = torch.randint(size=(2, 3), low=0, high = 10)
e

tensor([[0, 4, 0],
        [8, 4, 4]])

In [19]:
# sum
torch.sum(e)

# sum along column
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([ 4, 16])

In [ ]:
# mean
e = e.to(torch.float32)

torch.mean(e) # mean is possible only for float dtype

torch.mean(e, dim=0) # along col
torch.mean(e, dim=1) # along row

tensor(3.3333)

In [32]:
# median
torch.median(e)

# same logic follows to perform operation along row/col

# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [34]:
# product
torch.prod(e)

# st. deviation
torch.std(e)

# variance
torch.var(e)

tensor(9.0667)

In [36]:
# argmax
torch.argmax(e) # gives the position of largest element

# argmin
torch.argmin(e) # gives the position of smallest element

tensor(0)

### matrix operation

In [39]:
f = torch.randint(size=(2, 3), low=0, high=10)
g= torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[1, 0, 4],
        [9, 9, 6]])
tensor([[9, 9],
        [4, 1],
        [1, 0]])


In [40]:
# matrix multiplication
torch.matmul(f, g)

tensor([[ 13,   9],
        [123,  90]])

In [41]:
# dot product

v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

torch.dot(v1, v2)

tensor(11)

In [43]:
# transpose
torch.transpose(g, 0, 1)

tensor([[9, 4, 1],
        [9, 1, 0]])

In [45]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
# determinent
torch.det(h)

# inverse
torch.inverse(h)

tensor([[ 0.0000,  0.3333,  0.0000],
        [ 0.2500, -0.7500,  0.0000],
        [-0.4167,  1.1389,  0.3333]])