### Scalar Operation

In [9]:
import torch # type: ignore
x = torch.tensor([[1,2,3],[4,5,6]])

In [10]:
# addition
x + 2

# subtraction
x - 2

# multiplication
x * 3

# division
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [11]:
# int division
(x*100) // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

### Element wise Operation

In [12]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [13]:
print(a)
print(b)

tensor([[0.7815, 0.4103, 0.1317],
        [0.7118, 0.4271, 0.9830]])
tensor([[0.1724, 0.3666, 0.2044],
        [0.6603, 0.8798, 0.3481]])


In [14]:
# addition
a+b

# subtraction
a-b

# multiplication
a*b

# division
a/b

# power
a ** b

tensor([[0.9584, 0.7214, 0.6608],
        [0.7990, 0.4731, 0.9940]])

In [15]:
## other operations

c = torch.tensor([1, -2, 3, -4])

# abs
torch.abs(c)

tensor([1, 2, 3, 4])

### Reduction Operation

In [16]:
e = torch.randint(size=(2, 3), low=0, high = 10)
e

tensor([[0, 4, 0],
        [8, 4, 4]])

In [19]:
# sum
torch.sum(e)

# sum along column
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([ 4, 16])

In [ ]:
# mean
e = e.to(torch.float32)

torch.mean(e) # mean is possible only for float dtype

torch.mean(e, dim=0) # along col
torch.mean(e, dim=1) # along row

tensor(3.3333)

In [32]:
# median
torch.median(e)

# same logic follows to perform operation along row/col

# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [34]:
# product
torch.prod(e)

# st. deviation
torch.std(e)

# variance
torch.var(e)

tensor(9.0667)

In [36]:
# argmax
torch.argmax(e) # gives the position of largest element

# argmin
torch.argmin(e) # gives the position of smallest element

tensor(0)

### matrix operation

In [39]:
f = torch.randint(size=(2, 3), low=0, high=10)
g= torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[1, 0, 4],
        [9, 9, 6]])
tensor([[9, 9],
        [4, 1],
        [1, 0]])


In [40]:
# matrix multiplication
torch.matmul(f, g)

tensor([[ 13,   9],
        [123,  90]])

In [41]:
# dot product

v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

torch.dot(v1, v2)

tensor(11)

In [43]:
# transpose
torch.transpose(g, 0, 1)

tensor([[9, 4, 1],
        [9, 1, 0]])

In [45]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
# determinent
torch.det(h)

# inverse
torch.inverse(h)

tensor([[ 0.0000,  0.3333,  0.0000],
        [ 0.2500, -0.7500,  0.0000],
        [-0.4167,  1.1389,  0.3333]])

### Inplace Operations

In [46]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

In [47]:
m.add_(n)

tensor([[0.3682, 1.2122, 0.9443],
        [1.4122, 1.3909, 1.6772]])

In [49]:
m.relu_()

tensor([[0.3682, 1.2122, 0.9443],
        [1.4122, 1.3909, 1.6772]])

In [50]:
m

tensor([[0.3682, 1.2122, 0.9443],
        [1.4122, 1.3909, 1.6772]])

### Copying a tensor

In [51]:
x = n

In [52]:
# above operation has a problem that if I make a change in any one of the tensor then both will get affected (copy by reference)
print('x: ', id(x))
print('n: ', id(n))

x:  137088271782832
n:  137088271782832


In [53]:
# make use of clone to prevent that
y = n.clone()

### Tensor Operations on GPU

In [ ]:
device = torch.device('cuda')

# creating the tensor
torch.rand((2,3), device=device)

# moving an existing tensor to GPU
y.to(device)

### Reshaping Tensors

In [55]:
y.reshape(2, 1, 3)

tensor([[[0.1915, 0.3567, 0.9098]],

        [[0.5407, 0.3990, 0.7925]]])

In [57]:
# flatten
y.flatten()

tensor([0.1915, 0.3567, 0.9098, 0.5407, 0.3990, 0.7925])

In [58]:
z = torch.rand(2, 3, 4)
print(z)

z.permute(2, 0, 1)

tensor([[[0.8905, 0.6104, 0.1339, 0.9951],
         [0.5165, 0.5893, 0.2006, 0.0649],
         [0.5138, 0.2290, 0.6540, 0.1605]],

        [[0.4048, 0.9552, 0.6852, 0.4732],
         [0.9111, 0.3744, 0.2614, 0.9490],
         [0.7436, 0.5469, 0.2919, 0.0803]]])


tensor([[[0.8905, 0.5165, 0.5138],
         [0.4048, 0.9111, 0.7436]],

        [[0.6104, 0.5893, 0.2290],
         [0.9552, 0.3744, 0.5469]],

        [[0.1339, 0.2006, 0.6540],
         [0.6852, 0.2614, 0.2919]],

        [[0.9951, 0.0649, 0.1605],
         [0.4732, 0.9490, 0.0803]]])

In [60]:
# unsqeeze
img = torch.rand(226, 226, 3)

img.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [65]:
# squeeze
d = torch.rand(1, 20)

d.squeeze(0).shape

torch.Size([20])