### Scalar Operation

In [ ]:
import torch # type: ignore
x = torch.tensor([[1,2,3],[4,5,6]])

In [2]:
# addition
x + 2

# subtraction
x - 2

# multiplication
x * 3

# division
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [3]:
# int division
(x*100) // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

### Element wise Operation

In [4]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [5]:
print(a)
print(b)

tensor([[0.2601, 0.2362, 0.0747],
        [0.6030, 0.7133, 0.8836]])
tensor([[0.1812, 0.8551, 0.6773],
        [0.2911, 0.6956, 0.8881]])


In [7]:
# addition
a+b

# subtraction
a-b

# multiplication
a*b

# division
a/b

# power
a ** b

tensor([[0.7835, 0.2911, 0.1725],
        [0.8631, 0.7906, 0.8959]])

In [8]:
## other operations

c = torch.tensor([1, -2, 3, -4])

# abs
torch.abs(c)

tensor([1, 2, 3, 4])