In [ ]:
import torch # type: ignore

In [2]:
x = torch.tensor([[1,2,3], [4,5,6]])

x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
x.shape

torch.Size([2, 3])

In [4]:
torch.empty_like(x) # copies the shape of x and allocates the space in memory to create a empty tensor

tensor([[135744550849968, 135744550849968,      1154605296],
        [     1160788048,               0,      1163166928]])

In [5]:
# similarly
torch.zeros_like(x)

torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [12]:
# also
# torch.rand_like(x) # it'll break, because rand generates the float values and x has integers in it

torch.rand_like(x, dtype=torch.float32)

tensor([[0.5256, 0.8407, 0.2613],
        [0.7721, 0.5643, 0.3222]])

### Tensor DataTypes

In [8]:
x.dtype

torch.int64

In [9]:
# assign datatype
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [11]:
# converting to another dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])